export const GET_LOGS="GET_LOGS"
export const SET_LOADING="SET_LOADING"
export const LOGS_ERROR="LOGS_ERROR"
export const ADD_LOGS="ADD_LOGS"
export const RESET_ALL="RESET_ALL"
export const DELETE_ITEM="DELETE_ITEM"
